### ISSUE TITLE
Interest in first order statistics?

### ISSUE THREAD

**Issue by blowekamp** [InsightSoftwareConsortium/ITKTextureFeatures#3]
Nice work here, I look forward to the insight journal article.

Just wanted to see if there was any interest in a filter which computed first order statistics (mean, min, max, variance, sigma, skewness, kurtosis, and entropy) over a sliding window of a scalar image. They seem very much inline with the subject of this repo.

I have an implementation here:
https://github.com/blowekamp/itkTextureAnalysis/blob/master/include/itkTextureMovingHistogramImageFilter.h
https://github.com/blowekamp/itkTextureAnalysis/blob/master/include/itkTextureHistogram.h

If you are interested an I make a pull request with these classes with tests and cleanup ( create? ) documentation for them.

**Comment by jbvimort** [comment]
Thank you so much for your interest!

It looks like a great idea to integrate first order feature filters! And it is totally in the line with what we are doing right now!
We are currently working on integrating the existing filters into 3DSlicer, but as soon as we are done with that we can touch base in order to integrate your work?

**Comment by blowekamp** [comment]
Addressed in pr #12.
